### ISSUE TITLE
Remove from Kue-UI

### ISSUE THREAD

**Issue by michelem09** [lykmapipo/kue-unique#9]
If I try to remove a unique job from the Kue-UI and I try to re-create the unique job I receive this error:

>  Error controller Error: job "89" doesnt exist
>         at Command.callback (/Users/michele/Sites/pubcheck-kue/node_modules/kue/lib/queue/job.js:178:17)
>         at normal_reply (/Users/michele/Sites/pubcheck-kue/node_modules/redis/index.js:714:21)
>         at RedisClient.return_reply (/Users/michele/Sites/pubcheck-kue/node_modules/redis/index.js:816:9)
>         at JavascriptRedisParser.returnReply (/Users/michele/Sites/pubcheck-kue/node_modules/redis/index.js:188:18)
>         at JavascriptRedisParser.execute (/Users/michele/Sites/pubcheck-kue/node_modules/redis-parser/lib/parser.js:574:12)
>         at Socket.<anonymous> (/Users/michele/Sites/pubcheck-kue/node_modules/redis/index.js:267:27)
>         at emitOne (events.js:96:13)
>         at Socket.emit (events.js:188:7)
>         at readableAddChunk (_stream_readable.js:176:18)
>         at Socket.Readable.push (_stream_readable.js:134:10)
>         at TCP.onread (net.js:548:20)
>

**Comment by michelem09** [comment]
Found it.

On line 119 where you filter by unique job to be deleted `id` in some case (I did investigate why) is a `String` instead a `Number`

This is the fix:

`return uniqueJobsData[key] === parseInt(id, 10);`

I will send you a PR ASAP.

**Comment by michelem09** [comment]
Probably it is a String because it comes from the query url params.
